# Generated by Django 4.2.9 on 2024-02-07 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='review',
            name='review_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='review',
            name='show',
            field=models.IntegerField(default=0),
        ),
    ]
