# Generated by Django 5.0.2 on 2024-02-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_review_rating_review_review_content_review_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='image',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='title',
            field=models.CharField(default=''),
        ),
    ]
