# Generated by Django 5.0.2 on 2024-02-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_watchlist_image_watchlist_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='image',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
